name: Upload Python Package

on:
  push:
    tags:
      - 'v*.*.*'
    
  workflow_dispatch:

# 添加显式权限声明
permissions:
  contents: write  # 需要写入仓库内容的权限
  packages: write  # 如果需要发布到 GitHub Packages 则需要此权限

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Get Version
      id: version
      run: |
        echo "VERSION=$(pip --version)" >> $GITHUB_OUTPUT
        echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build distribution
      run: |
        python -m build
      
    # 使用更可靠的方法上传到 GitHub Release
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
        tag_name: ${{ steps.version.outputs.TAG_NAME }}
      
    - name: Publish to PyPI
      run: |
        python -m twine upload dist/* --repository-url https://upload.pypi.org/legacy/ --username __token__ --password ${{ secrets.PYPI_TOKEN }}